#!/usr/bin/env bash

# dependencies - webtorrent, mpv, xmllint

mkdir -p $HOME/.cache/subsplease     # make a new folder for temporary

menu="dmenu -i -l 25 -b"
baseurl="https://subsplease.org/rss/"
cachedir="$HOME/.cache/subsplease"

# get rss file from subsplease
curl -s $baseurl > $cachedir/rss.xml
xmllint --xpath "//item" $cachedir/rss.xml > $cachedir/tmp.xml    # format rss.xml to make look pretty

# get titles
grep -o '<title>.*</title>' $cachedir/tmp.xml | 
  sed 's/<title>.............//g' | 
  sed 's/.................title>//g' > $cachedir/title

# selecting name of the anime
paste -d\  $cachedir/title | 
  fzf --tac > $cachedir/anime

# remove brackets
#code=$(grep -oP '\[.*?]' $cachedir/anime | head -n 2 | tail -1 | sed 's/[][]//g')
code=$(cat $cachedir/anime)

# get magnet link with your selected anime
grep -i -C 0 "$code" $cachedir/tmp.xml > $cachedir/match
magnet=$(grep -Po "magnet:\?xt=urn:btih:[a-zA-Z0-9]*" $cachedir/match)

# playing a video
peerflix -k "$magnet"
